from ordering.models import *

small = SizeID.objects.create(size="small")
large = SizeID.objects.create(size="large")


regular= BaseID.objects.create(base="regular")
sicilian= BaseID.objects.create(base="sicilian")


cheese = TypeID.objects.create(type="cheese")
one_topping = TypeID.objects.create(type="one topping")
two_toppings = TypeID.objects.create(type="two toppings")
three_toppings = TypeID.objects.create(type="three toppings")
special= TypeID.objects.create(type="special")


pepperoni = Toppings.objects.create(topping="pepperoni")
sausage = Toppings.objects.create(topping="sausage")
mushrooms = Toppings.objects.create(topping="mushrooms")
onions = Toppings.objects.create(topping="onions")
hams = Toppings.objects.create(topping="hams")
canadian_bacon = Toppings.objects.create(topping="canadian bacon")
pineapple = Toppings.objects.create(topping="pineapple")
eggplant = Toppings.objects.create(topping="eggplant")
tomato_and_basil = Toppings.objects.create(topping="tomato and basil")
green_peppers = Toppings.objects.create(topping="green peppers")
hamburger = Toppings.objects.create(topping="hamburger")
spinach = Toppings.objects.create(topping="spinach")
artichoke = Toppings.objects.create(topping="artichoke")
buffalo_chicken = Toppings.objects.create(topping="buffalo chicken")
barbecue_chicken = Toppings.objects.create(topping="barbecue chicken")
anchovies = Toppings.objects.create(topping="anchovies")
black_olives = Toppings.objects.create(topping="black olives")
fresh_garlic = Toppings.objects.create(topping="fresh garlic")
zuchini = Toppings.objects.create(topping="zucchini")

extra_cheese = Condiments.objects.create(condiment="extra cheese")
mushrooms = Condiments.objects.create(condiment="mushrooms")
green_peppers = Condiments.objects.create(condiment="green peppers")
onions = Condiments.objects.create(condiment="onions")

Pizza.objects.create(base= regular, pizza_size=small, pizza_type= cheese, pizza_price=12.20)
Pizza.objects.create(base= regular, pizza_size=large, pizza_type= cheese, pizza_price=17.45)
Pizza.objects.create(base= regular, pizza_size=small, pizza_type= one_topping, pizza_price=13.20)
Pizza.objects.create(base= regular, pizza_size=large, pizza_type= one_topping, pizza_price=19.45)
Pizza.objects.create(base= regular, pizza_size=small, pizza_type= two_toppings, pizza_price=14.70)
Pizza.objects.create(base= regular, pizza_size=large, pizza_type= two_toppings, pizza_price=21.45)
Pizza.objects.create(base= regular, pizza_size=small, pizza_type= three_toppings, pizza_price=15.70)
Pizza.objects.create(base= regular, pizza_size=large, pizza_type= three_toppings, pizza_price=23.45)
Pizza.objects.create(base= regular, pizza_size=small, pizza_type= special, pizza_price=17.25)
Pizza.objects.create(base= regular, pizza_size=large, pizza_type= special, pizza_price=25.45)

Pizza.objects.create(base= sicilian, pizza_size=small, pizza_type= cheese, pizza_price=23.45)
Pizza.objects.create(base= sicilian, pizza_size=large, pizza_type= cheese, pizza_price=37.70)
Pizza.objects.create(base= sicilian, pizza_size=small, pizza_type= one_topping, pizza_price=25.45)
Pizza.objects.create(base= sicilian, pizza_size=large, pizza_type= one_topping, pizza_price=39.70)
Pizza.objects.create(base= sicilian, pizza_size=small, pizza_type= two_toppings, pizza_price=27.45)
Pizza.objects.create(base= sicilian, pizza_size=large, pizza_type= two_toppings, pizza_price=41.70)
Pizza.objects.create(base= sicilian, pizza_size=small, pizza_type= three_toppings, pizza_price=28.45)
Pizza.objects.create(base= sicilian, pizza_size=large, pizza_type= three_toppings, pizza_price=43.70)
Pizza.objects.create(base= sicilian, pizza_size=small, pizza_type= special, pizza_price=29.45)
Pizza.objects.create(base= sicilian, pizza_size=large, pizza_type= special, pizza_price=44.70)

Subs.objects.create(subs_size=small, subs_type="cheese", subs_price=6.50)
Subs.objects.create(subs_size=large, subs_type="cheese", subs_price=7.95)
Subs.objects.create(subs_size=small, subs_type="italian", subs_price=6.50)
Subs.objects.create(subs_size=large, subs_type="italian", subs_price=7.95)
Subs.objects.create(subs_size=small, subs_type="ham and cheese", subs_price=6.50)
Subs.objects.create(subs_size=large, subs_type="ham and cheese", subs_price=7.95)
Subs.objects.create(subs_size=small, subs_type="meatball", subs_price=6.50)
Subs.objects.create(subs_size=large, subs_type="meatball", subs_price=7.95)
Subs.objects.create(subs_size=small, subs_type="tuna", subs_price=6.50)
Subs.objects.create(subs_size=large, subs_type="tuna", subs_price=7.95)
Subs.objects.create(subs_size=small, subs_type="turkey", subs_price=7.50)
Subs.objects.create(subs_size=large, subs_type="turkey", subs_price=8.50)
Subs.objects.create(subs_size=small, subs_type="chicken parmigiana", subs_price=7.50)
Subs.objects.create(subs_size=large, subs_type="chicken parmigiana", subs_price=8.50)
Subs.objects.create(subs_size=small, subs_type="eggplant parmigiana", subs_price=6.50)
Subs.objects.create(subs_size=large, subs_type="eggplant parmigiana", subs_price=7.95)
Subs.objects.create(subs_size=small, subs_type="steak and cheese", subs_price=6.95)
Subs.objects.create(subs_size=large, subs_type="steak and cheese", subs_price=8.50)
Subs.objects.create(subs_size=large, subs_type="sausage, peppers and onions", subs_price=8.50)
Subs.objects.create(subs_size=small, subs_type="hamburger", subs_price=4.60)
Subs.objects.create(subs_size=large, subs_type="hamburger", subs_price=6.95)
Subs.objects.create(subs_size=small, subs_type="cheeseburger", subs_price=5.10)
Subs.objects.create(subs_size=large, subs_type="cheeseburger", subs_price=7.45)
Subs.objects.create(subs_size=small, subs_type="fried chicken", subs_price=6.95)
Subs.objects.create(subs_size=large, subs_type="fried chicken", subs_price=8.50)
Subs.objects.create(subs_size=small, subs_type="veggie", subs_price=6.95)
Subs.objects.create(subs_size=large, subs_type="veggie", subs_price=8.50)

Pasta.objects.create(pasta_type="baked ziti with mozzarella", pasta_price=6.50)
Pasta.objects.create(pasta_type="baked Ziti with meatballs", pasta_price=8.75)
Pasta.objects.create(pasta_type="baked ziti with chicken", pasta_price=9.75)

Salads.objects.create(salads_type="garden salad", salads_price=6.25)
Salads.objects.create(salads_type="greek salad", salads_price=8.25)
Salads.objects.create(salads_type="antipasto", salads_price=8.25)
Salads.objects.create(salads_type="salad with tuna", salads_price=8.25)

