# Generated by Django 2.1.7 on 2019-04-03 13:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0004_auto_20190402_2357'),
    ]

    operations = [
        migrations.CreateModel(
            name='PizzaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('complete', models.BooleanField(default=True)),
            ],
        ),
        migrations.RenameField(
            model_name='cart',
            old_name='platter_order',
            new_name='platters_order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pizza_order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='topping_order',
        ),
        migrations.AddField(
            model_name='cart',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AddField(
            model_name='pizza',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='ordering.Toppings'),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_order', to='ordering.Cart'),
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_order_types', to='ordering.Pizza'),
        ),
    ]
