# Generated by Django 2.1.7 on 2019-04-03 15:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0005_auto_20190403_1631'),
    ]

    operations = [
        migrations.CreateModel(
            name='PastaOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commplete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PlattersOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commplete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SaladsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commplete', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='SubsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('commplete', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='cart',
            name='pasta_order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='platters_order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='salads_order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='subs_order',
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_cart_order', to='ordering.Cart'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='pizza',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pizza_types', to='ordering.Pizza'),
        ),
        migrations.AddField(
            model_name='subsorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs_order', to='ordering.Cart'),
        ),
        migrations.AddField(
            model_name='subsorder',
            name='subs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subs_types', to='ordering.Subs'),
        ),
        migrations.AddField(
            model_name='saladsorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salads_cart_order', to='ordering.Cart'),
        ),
        migrations.AddField(
            model_name='saladsorder',
            name='salads',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='salads_types', to='ordering.Salads'),
        ),
        migrations.AddField(
            model_name='plattersorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platters_cart_order', to='ordering.Cart'),
        ),
        migrations.AddField(
            model_name='plattersorder',
            name='platters',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='platters_types', to='ordering.DinnerPlatters'),
        ),
        migrations.AddField(
            model_name='pastaorder',
            name='cart',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasta_cart_order', to='ordering.Cart'),
        ),
        migrations.AddField(
            model_name='pastaorder',
            name='subs',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasta_types', to='ordering.Subs'),
        ),
    ]
