# Generated by Django 2.1.7 on 2019-04-09 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0006_auto_20190403_1858'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pizza',
            name='toppings',
        ),
        migrations.AddField(
            model_name='pizzaorder',
            name='toppings',
            field=models.ManyToManyField(blank=True, related_name='toppings', to='ordering.Toppings'),
        ),
    ]
