# Generated by Django 2.1.7 on 2019-04-12 16:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0008_auto_20190410_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pastaorder',
            old_name='commplete',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='plattersorder',
            old_name='commplete',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='saladsorder',
            old_name='commplete',
            new_name='complete',
        ),
        migrations.RenameField(
            model_name='subsorder',
            old_name='commplete',
            new_name='complete',
        ),
    ]
