# Generated by Django 2.1.7 on 2019-04-12 16:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0009_auto_20190412_1904'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pastaorder',
            name='pasta',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pasta_types', to='ordering.Pasta'),
        ),
    ]
