# Generated by Django 2.1.7 on 2019-04-25 01:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0011_auto_20190425_0422'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizzaorder',
            name='toppings_1',
            field=models.ForeignKey(default=78, on_delete=django.db.models.deletion.CASCADE, related_name='toppings_1', to='ordering.Toppings'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='toppings_2',
            field=models.ForeignKey(default=78, on_delete=django.db.models.deletion.CASCADE, related_name='toppings_2', to='ordering.Toppings'),
        ),
        migrations.AlterField(
            model_name='pizzaorder',
            name='toppings_3',
            field=models.ForeignKey(default=78, on_delete=django.db.models.deletion.CASCADE, related_name='toppings_3', to='ordering.Toppings'),
        ),
    ]
