# Generated by Django 2.1.7 on 2019-04-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0012_auto_20190425_0424'),
    ]

    operations = [
        migrations.AddField(
            model_name='subsorder',
            name='extra_cheese',
            field=models.BooleanField(default=False),
        ),
    ]
