# Generated by Django 2.1.7 on 2019-05-01 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ordering', '0014_auto_20190426_1016'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeid_subs',
            name='can_add_condiments',
            field=models.BooleanField(default=False),
        ),
    ]
